services:
  - type: web
    name: chrono-compiler-n8n
    env: docker
    plan: starter
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
    envVars:
      - key: N8N_PORT
        value: 10000
      - key: WEBHOOK_URL
        value: https://chrono-compiler-n8n.onrender.com
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "saptarshiroy39@gmail.com"
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
